//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("CommunticateModel", "FK__CommuterD__Commu__31EC6D26", "Commuter", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Commuticate.Repository.Commuter), "CommuterData", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Commuticate.Repository.CommuterData), true)]
[assembly: EdmRelationshipAttribute("CommunticateModel", "FK__Route__CommuterI__36B12243", "Commuter", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Commuticate.Repository.Commuter), "Route", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Commuticate.Repository.Route), true)]
[assembly: EdmRelationshipAttribute("CommunticateModel", "FK__RouteGrou__Commu__35BCFE0A", "Commuter", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Commuticate.Repository.Commuter), "RouteGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Commuticate.Repository.RouteGroup), true)]
[assembly: EdmRelationshipAttribute("CommunticateModel", "FK__Que__RouteGroupI__37A5467C", "RouteGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Commuticate.Repository.RouteGroup), "Que", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Commuticate.Repository.Que), true)]
[assembly: EdmRelationshipAttribute("CommunticateModel", "FK__QueSchedu__QueId__32E0915F", "Que", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Commuticate.Repository.Que), "QueSchedule", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Commuticate.Repository.QueSchedule), true)]
[assembly: EdmRelationshipAttribute("CommunticateModel", "FK__RouteGrou__Route__33D4B598", "RouteGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Commuticate.Repository.RouteGroup), "RouteGroupRoutes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Commuticate.Repository.RouteGroupRoute), true)]
[assembly: EdmRelationshipAttribute("CommunticateModel", "FK__RouteGrou__Route__34C8D9D1", "RouteGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Commuticate.Repository.RouteGroup), "RouteGroupRoutes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Commuticate.Repository.RouteGroupRoute), true)]

#endregion

namespace Commuticate.Repository
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Commuter> Commuters
        {
            get
            {
                if ((_Commuters == null))
                {
                    _Commuters = base.CreateObjectSet<Commuter>("Commuters");
                }
                return _Commuters;
            }
        }
        private ObjectSet<Commuter> _Commuters;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CommuterData> CommuterDatas
        {
            get
            {
                if ((_CommuterDatas == null))
                {
                    _CommuterDatas = base.CreateObjectSet<CommuterData>("CommuterDatas");
                }
                return _CommuterDatas;
            }
        }
        private ObjectSet<CommuterData> _CommuterDatas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Que> Ques
        {
            get
            {
                if ((_Ques == null))
                {
                    _Ques = base.CreateObjectSet<Que>("Ques");
                }
                return _Ques;
            }
        }
        private ObjectSet<Que> _Ques;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<QueSchedule> QueSchedules
        {
            get
            {
                if ((_QueSchedules == null))
                {
                    _QueSchedules = base.CreateObjectSet<QueSchedule>("QueSchedules");
                }
                return _QueSchedules;
            }
        }
        private ObjectSet<QueSchedule> _QueSchedules;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Route> Routes
        {
            get
            {
                if ((_Routes == null))
                {
                    _Routes = base.CreateObjectSet<Route>("Routes");
                }
                return _Routes;
            }
        }
        private ObjectSet<Route> _Routes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RouteGroup> RouteGroups
        {
            get
            {
                if ((_RouteGroups == null))
                {
                    _RouteGroups = base.CreateObjectSet<RouteGroup>("RouteGroups");
                }
                return _RouteGroups;
            }
        }
        private ObjectSet<RouteGroup> _RouteGroups;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RouteGroupRoute> RouteGroupRoutes
        {
            get
            {
                if ((_RouteGroupRoutes == null))
                {
                    _RouteGroupRoutes = base.CreateObjectSet<RouteGroupRoute>("RouteGroupRoutes");
                }
                return _RouteGroupRoutes;
            }
        }
        private ObjectSet<RouteGroupRoute> _RouteGroupRoutes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Commuters EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCommuters(Commuter commuter)
        {
            base.AddObject("Commuters", commuter);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CommuterDatas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCommuterDatas(CommuterData commuterData)
        {
            base.AddObject("CommuterDatas", commuterData);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ques EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToQues(Que que)
        {
            base.AddObject("Ques", que);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the QueSchedules EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToQueSchedules(QueSchedule queSchedule)
        {
            base.AddObject("QueSchedules", queSchedule);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Routes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRoutes(Route route)
        {
            base.AddObject("Routes", route);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RouteGroups EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRouteGroups(RouteGroup routeGroup)
        {
            base.AddObject("RouteGroups", routeGroup);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RouteGroupRoutes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRouteGroupRoutes(RouteGroupRoute routeGroupRoute)
        {
            base.AddObject("RouteGroupRoutes", routeGroupRoute);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CommunticateModel", Name="Commuter")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Commuter : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Commuter object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="fullName">Initial value of the FullName property.</param>
        public static Commuter CreateCommuter(global::System.Int32 id, global::System.String email, global::System.String password, global::System.String fullName)
        {
            Commuter commuter = new Commuter();
            commuter.Id = id;
            commuter.Email = email;
            commuter.Password = password;
            commuter.FullName = fullName;
            return commuter;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FullName
        {
            get
            {
                return _FullName;
            }
            set
            {
                OnFullNameChanging(value);
                ReportPropertyChanging("FullName");
                _FullName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FullName");
                OnFullNameChanged();
            }
        }
        private global::System.String _FullName;
        partial void OnFullNameChanging(global::System.String value);
        partial void OnFullNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CommunticateModel", "FK__CommuterD__Commu__31EC6D26", "CommuterData")]
        public EntityCollection<CommuterData> CommuterDatas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CommuterData>("CommunticateModel.FK__CommuterD__Commu__31EC6D26", "CommuterData");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CommuterData>("CommunticateModel.FK__CommuterD__Commu__31EC6D26", "CommuterData", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CommunticateModel", "FK__Route__CommuterI__36B12243", "Route")]
        public EntityCollection<Route> Routes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Route>("CommunticateModel.FK__Route__CommuterI__36B12243", "Route");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Route>("CommunticateModel.FK__Route__CommuterI__36B12243", "Route", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CommunticateModel", "FK__RouteGrou__Commu__35BCFE0A", "RouteGroup")]
        public EntityCollection<RouteGroup> RouteGroups
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RouteGroup>("CommunticateModel.FK__RouteGrou__Commu__35BCFE0A", "RouteGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RouteGroup>("CommunticateModel.FK__RouteGrou__Commu__35BCFE0A", "RouteGroup", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CommunticateModel", Name="CommuterData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CommuterData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CommuterData object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="commuterId">Initial value of the CommuterId property.</param>
        /// <param name="dataType">Initial value of the DataType property.</param>
        /// <param name="dataValue">Initial value of the DataValue property.</param>
        public static CommuterData CreateCommuterData(global::System.Int32 id, global::System.Int32 commuterId, global::System.String dataType, global::System.String dataValue)
        {
            CommuterData commuterData = new CommuterData();
            commuterData.Id = id;
            commuterData.CommuterId = commuterId;
            commuterData.DataType = dataType;
            commuterData.DataValue = dataValue;
            return commuterData;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CommuterId
        {
            get
            {
                return _CommuterId;
            }
            set
            {
                OnCommuterIdChanging(value);
                ReportPropertyChanging("CommuterId");
                _CommuterId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CommuterId");
                OnCommuterIdChanged();
            }
        }
        private global::System.Int32 _CommuterId;
        partial void OnCommuterIdChanging(global::System.Int32 value);
        partial void OnCommuterIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DataType
        {
            get
            {
                return _DataType;
            }
            set
            {
                OnDataTypeChanging(value);
                ReportPropertyChanging("DataType");
                _DataType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DataType");
                OnDataTypeChanged();
            }
        }
        private global::System.String _DataType;
        partial void OnDataTypeChanging(global::System.String value);
        partial void OnDataTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DataValue
        {
            get
            {
                return _DataValue;
            }
            set
            {
                OnDataValueChanging(value);
                ReportPropertyChanging("DataValue");
                _DataValue = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DataValue");
                OnDataValueChanged();
            }
        }
        private global::System.String _DataValue;
        partial void OnDataValueChanging(global::System.String value);
        partial void OnDataValueChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CommunticateModel", "FK__CommuterD__Commu__31EC6D26", "Commuter")]
        public Commuter Commuter
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Commuter>("CommunticateModel.FK__CommuterD__Commu__31EC6D26", "Commuter").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Commuter>("CommunticateModel.FK__CommuterD__Commu__31EC6D26", "Commuter").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Commuter> CommuterReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Commuter>("CommunticateModel.FK__CommuterD__Commu__31EC6D26", "Commuter");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Commuter>("CommunticateModel.FK__CommuterD__Commu__31EC6D26", "Commuter", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CommunticateModel", Name="Que")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Que : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Que object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="routeGroupId">Initial value of the RouteGroupId property.</param>
        public static Que CreateQue(global::System.Int32 id, global::System.String description, global::System.Int32 routeGroupId)
        {
            Que que = new Que();
            que.Id = id;
            que.Description = description;
            que.RouteGroupId = routeGroupId;
            return que;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RouteGroupId
        {
            get
            {
                return _RouteGroupId;
            }
            set
            {
                OnRouteGroupIdChanging(value);
                ReportPropertyChanging("RouteGroupId");
                _RouteGroupId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RouteGroupId");
                OnRouteGroupIdChanged();
            }
        }
        private global::System.Int32 _RouteGroupId;
        partial void OnRouteGroupIdChanging(global::System.Int32 value);
        partial void OnRouteGroupIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CommunticateModel", "FK__Que__RouteGroupI__37A5467C", "RouteGroup")]
        public RouteGroup RouteGroup
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RouteGroup>("CommunticateModel.FK__Que__RouteGroupI__37A5467C", "RouteGroup").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RouteGroup>("CommunticateModel.FK__Que__RouteGroupI__37A5467C", "RouteGroup").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<RouteGroup> RouteGroupReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RouteGroup>("CommunticateModel.FK__Que__RouteGroupI__37A5467C", "RouteGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<RouteGroup>("CommunticateModel.FK__Que__RouteGroupI__37A5467C", "RouteGroup", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CommunticateModel", "FK__QueSchedu__QueId__32E0915F", "QueSchedule")]
        public EntityCollection<QueSchedule> QueSchedules
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<QueSchedule>("CommunticateModel.FK__QueSchedu__QueId__32E0915F", "QueSchedule");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<QueSchedule>("CommunticateModel.FK__QueSchedu__QueId__32E0915F", "QueSchedule", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CommunticateModel", Name="QueSchedule")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class QueSchedule : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new QueSchedule object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="queId">Initial value of the QueId property.</param>
        /// <param name="onDays">Initial value of the OnDays property.</param>
        /// <param name="atTime">Initial value of the AtTime property.</param>
        /// <param name="notifyEmail">Initial value of the NotifyEmail property.</param>
        /// <param name="notifySMS">Initial value of the NotifySMS property.</param>
        /// <param name="notifyTwitter">Initial value of the NotifyTwitter property.</param>
        /// <param name="runOnce">Initial value of the RunOnce property.</param>
        public static QueSchedule CreateQueSchedule(global::System.Int32 id, global::System.Int32 queId, global::System.String onDays, global::System.TimeSpan atTime, global::System.Boolean notifyEmail, global::System.Boolean notifySMS, global::System.Boolean notifyTwitter, global::System.Boolean runOnce)
        {
            QueSchedule queSchedule = new QueSchedule();
            queSchedule.Id = id;
            queSchedule.QueId = queId;
            queSchedule.OnDays = onDays;
            queSchedule.AtTime = atTime;
            queSchedule.NotifyEmail = notifyEmail;
            queSchedule.NotifySMS = notifySMS;
            queSchedule.NotifyTwitter = notifyTwitter;
            queSchedule.RunOnce = runOnce;
            return queSchedule;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 QueId
        {
            get
            {
                return _QueId;
            }
            set
            {
                OnQueIdChanging(value);
                ReportPropertyChanging("QueId");
                _QueId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QueId");
                OnQueIdChanged();
            }
        }
        private global::System.Int32 _QueId;
        partial void OnQueIdChanging(global::System.Int32 value);
        partial void OnQueIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OnDays
        {
            get
            {
                return _OnDays;
            }
            set
            {
                OnOnDaysChanging(value);
                ReportPropertyChanging("OnDays");
                _OnDays = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OnDays");
                OnOnDaysChanged();
            }
        }
        private global::System.String _OnDays;
        partial void OnOnDaysChanging(global::System.String value);
        partial void OnOnDaysChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan AtTime
        {
            get
            {
                return _AtTime;
            }
            set
            {
                OnAtTimeChanging(value);
                ReportPropertyChanging("AtTime");
                _AtTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AtTime");
                OnAtTimeChanged();
            }
        }
        private global::System.TimeSpan _AtTime;
        partial void OnAtTimeChanging(global::System.TimeSpan value);
        partial void OnAtTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean NotifyEmail
        {
            get
            {
                return _NotifyEmail;
            }
            set
            {
                OnNotifyEmailChanging(value);
                ReportPropertyChanging("NotifyEmail");
                _NotifyEmail = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NotifyEmail");
                OnNotifyEmailChanged();
            }
        }
        private global::System.Boolean _NotifyEmail;
        partial void OnNotifyEmailChanging(global::System.Boolean value);
        partial void OnNotifyEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean NotifySMS
        {
            get
            {
                return _NotifySMS;
            }
            set
            {
                OnNotifySMSChanging(value);
                ReportPropertyChanging("NotifySMS");
                _NotifySMS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NotifySMS");
                OnNotifySMSChanged();
            }
        }
        private global::System.Boolean _NotifySMS;
        partial void OnNotifySMSChanging(global::System.Boolean value);
        partial void OnNotifySMSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean NotifyTwitter
        {
            get
            {
                return _NotifyTwitter;
            }
            set
            {
                OnNotifyTwitterChanging(value);
                ReportPropertyChanging("NotifyTwitter");
                _NotifyTwitter = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NotifyTwitter");
                OnNotifyTwitterChanged();
            }
        }
        private global::System.Boolean _NotifyTwitter;
        partial void OnNotifyTwitterChanging(global::System.Boolean value);
        partial void OnNotifyTwitterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean RunOnce
        {
            get
            {
                return _RunOnce;
            }
            set
            {
                OnRunOnceChanging(value);
                ReportPropertyChanging("RunOnce");
                _RunOnce = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RunOnce");
                OnRunOnceChanged();
            }
        }
        private global::System.Boolean _RunOnce;
        partial void OnRunOnceChanging(global::System.Boolean value);
        partial void OnRunOnceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastRun
        {
            get
            {
                return _LastRun;
            }
            set
            {
                OnLastRunChanging(value);
                ReportPropertyChanging("LastRun");
                _LastRun = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastRun");
                OnLastRunChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastRun;
        partial void OnLastRunChanging(Nullable<global::System.DateTime> value);
        partial void OnLastRunChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CommunticateModel", "FK__QueSchedu__QueId__32E0915F", "Que")]
        public Que Que
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Que>("CommunticateModel.FK__QueSchedu__QueId__32E0915F", "Que").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Que>("CommunticateModel.FK__QueSchedu__QueId__32E0915F", "Que").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Que> QueReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Que>("CommunticateModel.FK__QueSchedu__QueId__32E0915F", "Que");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Que>("CommunticateModel.FK__QueSchedu__QueId__32E0915F", "Que", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CommunticateModel", Name="Route")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Route : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Route object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="commuterId">Initial value of the CommuterId property.</param>
        public static Route CreateRoute(global::System.Int32 id, global::System.String description, global::System.Int32 commuterId)
        {
            Route route = new Route();
            route.Id = id;
            route.Description = description;
            route.CommuterId = commuterId;
            return route;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CommuterId
        {
            get
            {
                return _CommuterId;
            }
            set
            {
                OnCommuterIdChanging(value);
                ReportPropertyChanging("CommuterId");
                _CommuterId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CommuterId");
                OnCommuterIdChanged();
            }
        }
        private global::System.Int32 _CommuterId;
        partial void OnCommuterIdChanging(global::System.Int32 value);
        partial void OnCommuterIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CommunticateModel", "FK__Route__CommuterI__36B12243", "Commuter")]
        public Commuter Commuter
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Commuter>("CommunticateModel.FK__Route__CommuterI__36B12243", "Commuter").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Commuter>("CommunticateModel.FK__Route__CommuterI__36B12243", "Commuter").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Commuter> CommuterReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Commuter>("CommunticateModel.FK__Route__CommuterI__36B12243", "Commuter");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Commuter>("CommunticateModel.FK__Route__CommuterI__36B12243", "Commuter", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CommunticateModel", Name="RouteGroup")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RouteGroup : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RouteGroup object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="commuterId">Initial value of the CommuterId property.</param>
        public static RouteGroup CreateRouteGroup(global::System.Int32 id, global::System.String description, global::System.Int32 commuterId)
        {
            RouteGroup routeGroup = new RouteGroup();
            routeGroup.Id = id;
            routeGroup.Description = description;
            routeGroup.CommuterId = commuterId;
            return routeGroup;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CommuterId
        {
            get
            {
                return _CommuterId;
            }
            set
            {
                OnCommuterIdChanging(value);
                ReportPropertyChanging("CommuterId");
                _CommuterId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CommuterId");
                OnCommuterIdChanged();
            }
        }
        private global::System.Int32 _CommuterId;
        partial void OnCommuterIdChanging(global::System.Int32 value);
        partial void OnCommuterIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CommunticateModel", "FK__RouteGrou__Commu__35BCFE0A", "Commuter")]
        public Commuter Commuter
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Commuter>("CommunticateModel.FK__RouteGrou__Commu__35BCFE0A", "Commuter").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Commuter>("CommunticateModel.FK__RouteGrou__Commu__35BCFE0A", "Commuter").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Commuter> CommuterReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Commuter>("CommunticateModel.FK__RouteGrou__Commu__35BCFE0A", "Commuter");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Commuter>("CommunticateModel.FK__RouteGrou__Commu__35BCFE0A", "Commuter", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CommunticateModel", "FK__Que__RouteGroupI__37A5467C", "Que")]
        public EntityCollection<Que> Ques
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Que>("CommunticateModel.FK__Que__RouteGroupI__37A5467C", "Que");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Que>("CommunticateModel.FK__Que__RouteGroupI__37A5467C", "Que", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CommunticateModel", "FK__RouteGrou__Route__33D4B598", "RouteGroupRoutes")]
        public EntityCollection<RouteGroupRoute> RouteGroupRoutes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RouteGroupRoute>("CommunticateModel.FK__RouteGrou__Route__33D4B598", "RouteGroupRoutes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RouteGroupRoute>("CommunticateModel.FK__RouteGrou__Route__33D4B598", "RouteGroupRoutes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CommunticateModel", "FK__RouteGrou__Route__34C8D9D1", "RouteGroupRoutes")]
        public EntityCollection<RouteGroupRoute> RouteGroupRoutes1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RouteGroupRoute>("CommunticateModel.FK__RouteGrou__Route__34C8D9D1", "RouteGroupRoutes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RouteGroupRoute>("CommunticateModel.FK__RouteGrou__Route__34C8D9D1", "RouteGroupRoutes", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CommunticateModel", Name="RouteGroupRoute")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RouteGroupRoute : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RouteGroupRoute object.
        /// </summary>
        /// <param name="routeGroupId">Initial value of the RouteGroupId property.</param>
        /// <param name="routeId">Initial value of the RouteId property.</param>
        public static RouteGroupRoute CreateRouteGroupRoute(global::System.Int32 routeGroupId, global::System.Int32 routeId)
        {
            RouteGroupRoute routeGroupRoute = new RouteGroupRoute();
            routeGroupRoute.RouteGroupId = routeGroupId;
            routeGroupRoute.RouteId = routeId;
            return routeGroupRoute;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RouteGroupId
        {
            get
            {
                return _RouteGroupId;
            }
            set
            {
                if (_RouteGroupId != value)
                {
                    OnRouteGroupIdChanging(value);
                    ReportPropertyChanging("RouteGroupId");
                    _RouteGroupId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RouteGroupId");
                    OnRouteGroupIdChanged();
                }
            }
        }
        private global::System.Int32 _RouteGroupId;
        partial void OnRouteGroupIdChanging(global::System.Int32 value);
        partial void OnRouteGroupIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RouteId
        {
            get
            {
                return _RouteId;
            }
            set
            {
                if (_RouteId != value)
                {
                    OnRouteIdChanging(value);
                    ReportPropertyChanging("RouteId");
                    _RouteId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RouteId");
                    OnRouteIdChanged();
                }
            }
        }
        private global::System.Int32 _RouteId;
        partial void OnRouteIdChanging(global::System.Int32 value);
        partial void OnRouteIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Order
        {
            get
            {
                return _Order;
            }
            set
            {
                OnOrderChanging(value);
                ReportPropertyChanging("Order");
                _Order = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Order");
                OnOrderChanged();
            }
        }
        private Nullable<global::System.Int32> _Order;
        partial void OnOrderChanging(Nullable<global::System.Int32> value);
        partial void OnOrderChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CommunticateModel", "FK__RouteGrou__Route__33D4B598", "RouteGroup")]
        public RouteGroup RouteGroup
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RouteGroup>("CommunticateModel.FK__RouteGrou__Route__33D4B598", "RouteGroup").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RouteGroup>("CommunticateModel.FK__RouteGrou__Route__33D4B598", "RouteGroup").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<RouteGroup> RouteGroupReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RouteGroup>("CommunticateModel.FK__RouteGrou__Route__33D4B598", "RouteGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<RouteGroup>("CommunticateModel.FK__RouteGrou__Route__33D4B598", "RouteGroup", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CommunticateModel", "FK__RouteGrou__Route__34C8D9D1", "RouteGroup")]
        public RouteGroup RouteGroup1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RouteGroup>("CommunticateModel.FK__RouteGrou__Route__34C8D9D1", "RouteGroup").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RouteGroup>("CommunticateModel.FK__RouteGrou__Route__34C8D9D1", "RouteGroup").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<RouteGroup> RouteGroup1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RouteGroup>("CommunticateModel.FK__RouteGrou__Route__34C8D9D1", "RouteGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<RouteGroup>("CommunticateModel.FK__RouteGrou__Route__34C8D9D1", "RouteGroup", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
